# language
language: python
python:
  - "3.7.10"
# service
services:
   - docker
# install docker-compose
before_script: pip install docker-compose
# run command test in container django
script:
  - docker-compose run app sh -c "python manage.py test && flake8"
